name: Playwright Tests
on:

  # Cấu hình 1: Tự động chạy khi push code
  push:
    branches: [ main, master ]

  # Cấu hình 2: Tự động chay khi Pull Request - PR từ nhánh phụ vào main
  pull_request:
    branches: [ main, master ]
  
  # Cấu hình 3: Cho phép bấm nút chạy bằng tay
  workflow_dispatch:
    inputs:
      project:
        description: 'Chọn project cần chạy'
        type: choice
        required: true
        default: regression-ui
        options:
          - regression-ui
          - regression-api
        
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      WEB_URL: ${{ secrets.WEB_URL}}
      API_URL: ${{ secrets.API_URL}}
      ADMIN_USER: ${{ secrets.ADMIN_USER}}
      ADMIN_PASS: ${{ secrets.ADMIN_PASS}}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    # UI
    - name: Run Regression UI
      if: |
        github.event_name != 'workflow_dispatch' ||
        github.event.inputs.project == 'regression-ui'
      run: npx playwright test --project=regression-ui

    # API
    - name: Run Regression API
      if: |
        github.event_name != 'workflow_dispatch' ||
        github.event.inputs.project == 'regression-api'
      run: npx playwright test --project=regression-api

      
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30